/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class edu_njnu_JNITest */

#ifndef _Included_edu_njnu_JNITest
#define _Included_edu_njnu_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_njnu_JNITest
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_njnu_JNITest_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
