spring:
  application:
    name: DynamicDataSource
  profiles:
    active: dev
  datasource:
#    driver-class-name: org.sqlite.JDBC
#    jdbc-url: jdbc:sqlite:D:/zhuomian/test.db
    jdbc-url: jdbc:postgresql://localhost:5432/manage?stringtype=unspecified
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8900

mybatis:
  mapper-locations: classpath:mapper/*/*.xml

